# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/user/Documents/Python-programming/quick-point/ui\mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(846, 619)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 559))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 551))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wgtWeb = QtWebEngineWidgets.QWebEngineView(self.horizontalLayoutWidget)
        self.wgtWeb.setEnabled(False)
        self.wgtWeb.setObjectName("wgtWeb")
        self.horizontalLayout.addWidget(self.wgtWeb)
        self.txtMarkdown = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.txtMarkdown.setObjectName("txtMarkdown")
        self.horizontalLayout.addWidget(self.txtMarkdown)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 2)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menucolor = QtWidgets.QMenu(self.menu_3)
        self.menucolor.setObjectName("menucolor")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(mainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(mainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionEdit = QtWidgets.QAction(mainWindow)
        self.actionEdit.setCheckable(False)
        self.actionEdit.setObjectName("actionEdit")
        self.actionDisplay = QtWidgets.QAction(mainWindow)
        self.actionDisplay.setObjectName("actionDisplay")
        self.actionresize = QtWidgets.QAction(mainWindow)
        self.actionresize.setObjectName("actionresize")
        self.actioncrop = QtWidgets.QAction(mainWindow)
        self.actioncrop.setObjectName("actioncrop")
        self.actionadd = QtWidgets.QAction(mainWindow)
        self.actionadd.setObjectName("actionadd")
        self.actionstretch = QtWidgets.QAction(mainWindow)
        self.actionstretch.setObjectName("actionstretch")
        self.actionrotate = QtWidgets.QAction(mainWindow)
        self.actionrotate.setObjectName("actionrotate")
        self.actionGithub = QtWidgets.QAction(mainWindow)
        self.actionGithub.setObjectName("actionGithub")
        self.actionDracula = QtWidgets.QAction(mainWindow)
        self.actionDracula.setObjectName("actionDracula")
        self.actionPresentation = QtWidgets.QAction(mainWindow)
        self.actionPresentation.setObjectName("actionPresentation")
        self.actionTmp = QtWidgets.QAction(mainWindow)
        self.actionTmp.setObjectName("actionTmp")
        self.actionexportPPT = QtWidgets.QAction(mainWindow)
        self.actionexportPPT.setObjectName("actionexportPPT")
        self.actionimportPPT = QtWidgets.QAction(mainWindow)
        self.actionimportPPT.setObjectName("actionimportPPT")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionimportPPT)
        self.menu.addAction(self.actionexportPPT)
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionEdit)
        self.menu_2.addAction(self.actionDisplay)
        self.menucolor.addAction(self.actionadd)
        self.menu_3.addAction(self.actionresize)
        self.menu_3.addAction(self.actioncrop)
        self.menu_3.addAction(self.menucolor.menuAction())
        self.menu_3.addAction(self.actionstretch)
        self.menu_3.addAction(self.actionrotate)
        self.menu_4.addAction(self.actionGithub)
        self.menu_4.addAction(self.actionDracula)
        self.menu_4.addAction(self.actionPresentation)
        self.menu_4.addAction(self.actionTmp)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(mainWindow)
        self.actionopen.triggered.connect(mainWindow.openFile)
        self.actionsave.triggered.connect(mainWindow.saveFile)
        self.actionExit.triggered.connect(mainWindow.close)
        self.txtMarkdown.textChanged.connect(self.updateWeb)
        self.actionexportPPT.triggered.connect(self.exportPPT)
        self.actionimportPPT.triggered.connect(self.importPPT)
        self.actionDisplay.triggered.connect(self.displayFullScreen)
        self.actionGithub.triggered.connect(self.setTemplateGithub)
        self.actionDracula.triggered.connect(self.setTemplateDracula)
        self.actionPresentation.triggered.connect(self.setTemplatePresentation)
        self.actionTmp.triggered.connect(self.setTemplateTmp)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Quick Point"))
        self.menu.setTitle(_translate("mainWindow", "파일"))
        self.menu_2.setTitle(_translate("mainWindow", "화면모드"))
        self.menu_3.setTitle(_translate("mainWindow", "이미지"))
        self.menucolor.setTitle(_translate("mainWindow", "color"))
        self.menu_4.setTitle(_translate("mainWindow", "템플릿"))
        self.actionopen.setText(_translate("mainWindow", "열기(&O)"))
        self.actionopen.setShortcut(_translate("mainWindow", "Ctrl+O"))
        self.actionsave.setText(_translate("mainWindow", "저장(&S)"))
        self.actionsave.setShortcut(_translate("mainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("mainWindow", "종료(&X)"))
        self.actionExit.setShortcut(_translate("mainWindow", "Ctrl+X"))
        self.actionEdit.setText(_translate("mainWindow", "수정모드"))
        self.actionEdit.setShortcut(_translate("mainWindow", "Ctrl+E"))
        self.actionDisplay.setText(_translate("mainWindow", "보기모드(전체화면)"))
        self.actionDisplay.setShortcut(_translate("mainWindow", "F5"))
        self.actionresize.setText(_translate("mainWindow", "resize"))
        self.actioncrop.setText(_translate("mainWindow", "crop"))
        self.actionadd.setText(_translate("mainWindow", "RGB"))
        self.actionstretch.setText(_translate("mainWindow", "stretch"))
        self.actionrotate.setText(_translate("mainWindow", "rotate"))
        self.actionGithub.setText(_translate("mainWindow", "Github"))
        self.actionDracula.setText(_translate("mainWindow", "Dracula"))
        self.actionPresentation.setText(_translate("mainWindow", "Presentation"))
        self.actionTmp.setText(_translate("mainWindow", "tmp"))
        self.actionexportPPT.setText(_translate("mainWindow", "내보내기(to *.ppt)"))
        self.actionimportPPT.setText(_translate("mainWindow", "가져오기(from *.PPT)"))


from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
